Usamo\CatalogBundle\Entity\OrderItem:
  type: entity
  table: article_items
  repositoryClass: Usamo\OrderingBundle\Entity\Repository\OrderItemRepository
  fields:
    id:
      id: true
      type: integer
      unsigned: true
      nullable: false
      generator:
        strategy: AUTO
    order_id:
      type: integer
      unsigned: true
      nullable: false
    good_id:
      type: integer
      unsigned: true
      nullable: false
    quantity:
      type: integer
      unsigned: true
      nullable: false
    properties:
      type: string
      length: 255
      fixed: false
      nullable: false
lifecycleCallbacks: {  }