parameters:
#    usamo_ordering.example.class: Usamo\OrderingBundle\Example

services:
#    usamo_ordering.example:
#        class: %usamo_ordering.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
