Usamo\CatalogBundle\Entity\CatalogueImage:
  type: entity
  table: catalogue_image
  repositoryClass: Usamo\CatalogBundle\Entity\Repository\CatalogueImageRepository
  fields:
    id:
      id: true
      type: integer
      unsigned: true
      nullable: false
      generator:
        strategy: AUTO
    src:
      type: string
      length: 255
      fixed: false
      nullable: false
    good_id:
      type: integer
      unsigned: true
      nullable: false
    is_main:
      type: integer
      unsigned: true
      nullable: false

lifecycleCallbacks: {  }