parameters:
#    usamo_catalog.example.class: Usamo\CatalogBundle\Example

services:
#    usamo_catalog.example:
#        class: %usamo_catalog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
